package com.voracious.ep1cG4m3;

/*  
 *  Ep1c G4m3 -- A parody platformer
 * 
 *  Copyright (C) 2011  Voracious Softworks
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.

 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>. 
 */

import java.awt.CardLayout;

import javax.swing.JFrame;
import javax.swing.JPanel;

import com.voracious.ep1cG4m3.framework.Screen;
import com.voracious.ep1cG4m3.utils.ScreenResultEvent;
import com.voracious.ep1cG4m3.screens.*;

/**
 * Main class. It makes the window and handles screen switching.
 * 
 * @author Voracious Softworks
 * @version 6/20/2011
 * @see JApplet
 */

public class Game extends JFrame implements ScreenResultEvent {
	
	/**
	 * Generated by Eclipse, It's to get rid of a warning.
	 */
	private static final long serialVersionUID = 4442265073346973079L;
	public static final int ID_MENU = 0;
	public static final int ID_PLAY = 1;
	public static final int ID_INSTRUCTIONS = 2;
	public static final int ID_LEVEL_EDITOR = 3;
	
	private JPanel cards;
	private int currentScreen;
	private Menu menu;
	private Play play;
	private Instructions instructions;
	private LevelEditor levelEditor;
	
	public Game(){
		setTitle("Ep1c G4m3");
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		setSize(500, 400);
		setLocationRelativeTo(null);
		setVisible(true);
		setResizable(false);
		
		menu = new Menu(ID_MENU, this);
		play = new Play(ID_PLAY, this);
		instructions = new Instructions(ID_INSTRUCTIONS, this);
		levelEditor = new LevelEditor(ID_LEVEL_EDITOR, this);
		currentScreen = ID_MENU;
		
		cards = new JPanel(new CardLayout());
		
		cards.add(getScreenFromId(ID_MENU), "menu");
		cards.add(getScreenFromId(ID_PLAY), "play");
		cards.add(getScreenFromId(ID_INSTRUCTIONS), "instructions");
		cards.add(getScreenFromId(ID_LEVEL_EDITOR), "level editor");
		getScreenFromId(getCurrentScreenId()).start();
		
		add(cards);
	}
	
	public static void main(String[] args){
		new Game();
	}
	
	@Override
	public void onScreenResult(int id, int result){
		switch(id){
			case ID_MENU:
				if(result == Menu.RESULT_PLAY)
					switchCurrentScreen(ID_PLAY);
				else if(result == Menu.RESULT_INSTRUCTIONS)
					switchCurrentScreen(ID_INSTRUCTIONS);
				else if(result == Menu.RESULT_LEVEL_EDITOR)
					switchCurrentScreen(ID_LEVEL_EDITOR);
				else
					System.out.println("ERROR: Unknown result type " + result);
				break;
			default:
				System.out.println("WARNING: Unknown id ("+id+ ") returned a result ("+result+")!");
				break;
		}
	}
	
	public int getCurrentScreenId(){
		return currentScreen;
	}
	
	public void switchCurrentScreen(int id){
		CardLayout cl = (CardLayout)cards.getLayout();
		getScreenFromId(currentScreen).stop();
		currentScreen = id;
		getScreenFromId(currentScreen).start();
		cl.show(cards, getNameFromId(currentScreen));
	}
	
	public Screen getScreenFromId(int id){
		switch(id){
			case ID_MENU:
				return menu;
			case ID_PLAY:
				return play;
			case ID_INSTRUCTIONS:
				return instructions;
			case ID_LEVEL_EDITOR:
				return levelEditor;
			default:
				System.out.println("ERROR: screen not found id:" + id);
				return null;
		}
	}
	
	public String getNameFromId(int id){
		switch(id){
			case ID_MENU:
				return "menu";
			case ID_PLAY:
				return "play";
			case ID_INSTRUCTIONS:
				return "instructions";
			case ID_LEVEL_EDITOR:
				return "level editor";
			default:
				System.out.println("ERROR: screen not found id:" + id);
				return null;
		}
	}
}
