package com.voracious.ep1cG4m3;

/*  
 *  Ep1c G4m3 -- A parody platformer
 * 
 *  Copyright (C) 2011  Voracious Softworks
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.

 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>. 
 */

import javax.swing.JApplet;

/**
 * Main class. It makes the window and handles screen switching.
 * 
 * @author Voracious Softworks
 */

public class Game extends JApplet {

	/**
	 * Generated by Eclipse, It's to get rid of a warning.
	 */
	private static final long serialVersionUID = 4442265073346973079L;

}
