package com.voracious.ep1cG4m3.screens;

import java.awt.Graphics;
import java.awt.Graphics2D;

import com.voracious.ep1cG4m3.framework.Screen;
import com.voracious.ep1cG4m3.utils.ScreenResultEvent;

public class Play extends Screen {

	/**
	 * Generated by eclipse 
	 */
	private static final long serialVersionUID = -1522258565924156537L;

	public Play(int id, ScreenResultEvent game) {
		super(id, game);
	}

	@Override
	public void start() {
	}

	@Override
	public void stop() {
	}
	
	@Override
	public void paint(Graphics g){
		super.paint(g);
		Graphics2D g2 = (Graphics2D) g;
		g2.drawString("Play screen", 10, 25);
	}
}
